-- Advanced Course in Drug-Resistant Tuberculosis (DR-TB)
--
-- Paste the whole file into phpMyAdmin (SQL tab, portal database) and run it.
--
-- Created as a DRAFT: clinical teaching carries ReSoK's name and issues ReSoK certificates,
-- so a ReSoK clinician reviews it against current WHO and NTLD-P guidance first, then
-- publishes it from the Academy admin. Learners cannot see or enrol in a draft.
--
-- Safe to run more than once: if a course with this slug already exists, nothing at all is
-- changed, so a re-run can never wipe learners' progress or a reviewer's edits.
--
-- 12 modules, generated from the development database on 28 Sep 2026.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET @existed = (SELECT COUNT(*) FROM academy_courses WHERE slug = 'advanced-course-in-drug-resistant-tuberculosis');

INSERT IGNORE INTO academy_courses
  (slug, title, summary, description, category, level, estimated_minutes, hero_image,
   members_only, certificate_enabled, pass_mark, status, published_at)
VALUES ('advanced-course-in-drug-resistant-tuberculosis', 'Advanced Course in Drug-Resistant Tuberculosis (DR-TB)',
  'A twelve-module clinical course on drug-resistant tuberculosis, from diagnosis and regimen design to adverse-event management and programme data.',
  'A structured professional learning programme covering the foundations, diagnosis, classification, treatment principles,\nmedicine safety, monitoring, infection prevention, patient-centred care and programme management of DR-TB.\nClinical safety: This educational course does not replace patient-specific clinical judgement,\ncurrent WHO guidance, national TB programme protocols or specialist review. Clinical recommendations must be checked against\nthe current applicable guidance.',
  'Tuberculosis', 'advanced', 114, NULL,
  0, 1, 80, 'draft', NULL);

SET @cid = (SELECT id FROM academy_courses WHERE slug = 'advanced-course-in-drug-resistant-tuberculosis');

-- Module 1: TB Foundations and the DR-TB Challenge
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'TB Foundations and the DR-TB Challenge', NULL, 1 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 1);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Tuberculosis: the disease', 'text', NULL,
    'Tuberculosis (TB) is an infectious disease caused predominantly by Mycobacterium tuberculosis. TB most commonly affects the lungs, but disease can occur in other organs. Transmission usually occurs through airborne particles generated by people with infectious pulmonary or laryngeal TB.\nLearners should distinguish TB infection from TB disease. Infection may exist without clinical disease, whereas TB disease occurs when organisms multiply and cause clinical or radiological disease. The distinction is important because diagnostic and preventive approaches differ.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Transmission, infection and disease', 'text', NULL,
    'Transmission is influenced by infectiousness, duration and frequency of exposure, ventilation and the susceptibility of exposed people. Infection-control measures therefore combine early identification, appropriate patient separation and respiratory precautions with environmental and administrative controls.\nA lung-health professional should be able to explain transmission without creating stigma: TB is a treatable disease, and patients should be supported rather than blamed.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'What makes TB drug-resistant?', 'text', NULL,
    'Drug resistance occurs when M. tuberculosis is resistant to one or more medicines used to treat TB. Resistance can arise through genetic mutations and can then be selected or transmitted. Inadequate regimens, interrupted treatment, poor drug absorption, drug interactions, poor-quality medicines and transmission of resistant organisms can all contribute to treatment failure or further resistance.\nDR-TB is not simply \'stronger TB\'. It requires a resistance-informed treatment strategy, careful monitoring and coordinated clinical, laboratory and public-health support.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Course orientation and clinical safety', 'text', NULL,
    'This course is an educational programme for health professionals and health-related learners. It is not a substitute for patient-specific prescribing, national TB-programme protocols, specialist consultation or current WHO guidance. Treatment eligibility, regimen selection, dosing, contraindications and monitoring must be checked against current guidance and local policy before clinical decisions are made.',
    2, 4 FROM DUAL WHERE @existed = 0;

-- Module 2: DR-TB Terminology, Classification and Epidemiology
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'DR-TB Terminology, Classification and Epidemiology', NULL, 2 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 2);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Resistance terminology', 'text', NULL,
    'Key categories include rifampicin-resistant TB (RR-TB), multidrug-resistant TB (MDR-TB), isoniazid-resistant TB and pre-XDR/XDR-TB categories defined by current WHO terminology. Learners should use current definitions rather than relying on older classifications that are still found in legacy documents.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'MDR-TB and RR-TB', 'text', NULL,
    'MDR-TB refers to resistance to at least isoniazid and rifampicin. RR-TB refers to rifampicin resistance detected by molecular or other testing, whether or not resistance to isoniazid has also been demonstrated. Clinically, RR-TB triggers a need for a DR-TB management pathway and additional resistance testing.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Pre-XDR and XDR-TB', 'text', NULL,
    'Current WHO definitions place emphasis on resistance to rifampicin plus additional resistance patterns, including resistance to fluoroquinolones and, for XDR-TB, resistance to key additional medicines. Because terminology and definitions have evolved, learners must use the definition in force in the applicable WHO and national guidance when documenting cases.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Epidemiology and equity', 'text', NULL,
    'DR-TB is both a clinical and public-health challenge. Delayed diagnosis, unequal access to testing and treatment, stigma, poverty, mobility and health-system barriers can affect outcomes. A patient-centred DR-TB programme therefore combines accurate diagnosis and effective treatment with social and service support.',
    2, 4 FROM DUAL WHERE @existed = 0;

-- Module 3: Screening, Diagnosis and Drug-Susceptibility Testing
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Screening, Diagnosis and Drug-Susceptibility Testing', NULL, 3 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 3);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Identifying people who need DR-TB evaluation', 'text', NULL,
    'People with TB who have a history of previous treatment, known contact with DR-TB, treatment failure or other programme-defined risk factors may require rapid evaluation for resistance. National algorithms determine who is tested and how results are acted upon.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Specimen collection and laboratory quality', 'text', NULL,
    'Good DR-TB diagnosis starts with an adequate specimen, correct labelling, safe handling, appropriate transport and a reliable laboratory network. Sputum quality, contamination, delays and incorrect packaging can undermine otherwise good diagnostic technology.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Rapid molecular testing', 'text', NULL,
    'WHO-recommended rapid molecular tests can detect M. tuberculosis and selected resistance markers much faster than conventional culture-based approaches. Xpert MTB/RIF and Xpert MTB/RIF Ultra are examples used in TB programmes. Molecular detection of rifampicin resistance should trigger an appropriate DR-TB diagnostic and clinical pathway rather than being treated as an isolated laboratory fact.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Line probe assays and culture', 'text', NULL,
    'Line probe assays can detect selected resistance-associated mutations. Culture remains important in many settings for confirmation, additional drug-susceptibility testing and monitoring. Phenotypic and genotypic tests answer related but different questions, and discordant results may require expert review.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Interpreting a diagnostic case', 'text', NULL,
    'Case: A patient with previous TB treatment has a molecular result showing M. tuberculosis with rifampicin resistance. The correct response is not to select a regimen from memory. Confirm the result according to the diagnostic algorithm, obtain the additional resistance information required by the applicable protocol, assess the patient clinically and link the patient promptly to the DR-TB treatment pathway.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 4: Treatment Principles and Current Regimen Framework
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Treatment Principles and Current Regimen Framework', NULL, 4 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 4);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Goals of DR-TB treatment', 'text', NULL,
    'The goals are to cure the patient, prevent death and disability, stop transmission, prevent emergence of additional resistance and minimize treatment-related harm. Effective treatment requires an adequate combination of active medicines and consistent monitoring.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Current WHO treatment landscape', 'text', NULL,
    'WHO updated its consolidated TB treatment guidance in 2025. The current framework includes shorter all-oral options for eligible MDR/RR-TB patients, including the 6-month BDLLfxC regimen and modified 9-month approaches in defined circumstances. Earlier 6-month BPaLM/BPaL recommendations remain important in the history of DR-TB care, but course users must apply the latest applicable WHO and national recommendations rather than assuming one regimen fits every patient.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'BPaLM and BPaL', 'text', NULL,
    'BPaLM contains bedaquiline, pretomanid, linezolid and moxifloxacin. BPaL contains bedaquiline, pretomanid and linezolid. These regimens have specific eligibility, resistance and safety considerations. Learners should understand the components and monitoring requirements but must not use this lesson as a stand-alone prescribing protocol.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Regimen selection', 'text', NULL,
    'Regimen selection depends on the patient\'s resistance pattern, previous exposure to medicines, age and pregnancy considerations, comorbidities, drug interactions, safety profile, availability and the applicable national programme protocol. The correct professional behaviour is to interpret the evidence and verify eligibility before treatment is initiated or modified.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Special populations', 'text', NULL,
    'Children, adolescents, pregnant or breastfeeding patients, people living with HIV, and patients with hepatic, renal, cardiac, neurological or psychiatric conditions may require additional assessment. Specialist and programme guidance should be followed.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 5: DR-TB Medicines and Safe Use
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'DR-TB Medicines and Safe Use', NULL, 5 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 5);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Bedaquiline', 'text', NULL,
    'Bedaquiline is a key medicine in modern DR-TB regimens. Important safety considerations include cardiac effects such as QT prolongation and clinically relevant drug interactions. Monitoring requirements must follow the current regimen and national protocol.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Pretomanid', 'text', NULL,
    'Pretomanid is used in specific all-oral DR-TB regimens. Its use is regimen- and eligibility-dependent. Liver safety, drug interactions, pregnancy considerations and other precautions must be checked against current product information and guideline recommendations.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Linezolid', 'text', NULL,
    'Linezolid is highly effective but requires careful safety monitoring. Important adverse effects include myelosuppression, peripheral neuropathy and optic toxicity. Symptoms such as new visual disturbance, unexplained cytopenia or worsening neuropathy require prompt clinical assessment.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Fluoroquinolones and other agents', 'text', NULL,
    'Moxifloxacin and other medicines may form part of individualized or shorter regimens depending on resistance and eligibility. Other agents may include clofazimine, cycloserine/terizidone and delamanid. The course emphasizes mechanism, role, adverse effects and monitoring rather than memorizing a single universal regimen.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Drug interactions and medication reconciliation', 'text', NULL,
    'A complete medication history should include prescribed medicines, over-the-counter products, traditional or herbal products and HIV medicines where relevant. Interactions can alter efficacy or toxicity. Medication reconciliation should be repeated when treatment changes occur.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 6: Adverse Drug Reactions and Pharmacovigilance
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Adverse Drug Reactions and Pharmacovigilance', NULL, 6 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 6);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Recognizing adverse events', 'text', NULL,
    'Learners should differentiate expected, mild effects from serious or potentially irreversible toxicity. A structured approach asks: What happened? When did it start? Which medicines are implicated? How severe is it? Are there danger signs? What monitoring is needed? What does the current protocol require?',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'QT prolongation', 'text', NULL,
    'Several medicines can affect cardiac repolarization. Risk is influenced by combinations, electrolyte abnormalities, underlying cardiac disease and other medicines. ECG and electrolyte monitoring should be performed when indicated by the regimen and protocol.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Neurological and visual toxicity', 'text', NULL,
    'Peripheral neuropathy and optic toxicity can be associated with medicines such as linezolid. New or worsening symptoms should be documented and escalated promptly because early recognition can reduce the risk of permanent impairment.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Haematological and hepatic toxicity', 'text', NULL,
    'Blood-count abnormalities and liver injury require timely laboratory assessment and clinical review. The response should follow the current adverse-event management protocol rather than an improvised medication change.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'aDSM and safety reporting', 'text', NULL,
    'Active TB drug-safety monitoring and management supports systematic detection, documentation, management and reporting of adverse events. Good pharmacovigilance improves individual patient safety and programme-level learning.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 7: Treatment Monitoring and Outcomes
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Treatment Monitoring and Outcomes', NULL, 7 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 7);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Baseline assessment', 'text', NULL,
    'Baseline evaluation should establish disease status, resistance information, previous treatment exposure, comorbidities, pregnancy status where applicable, concurrent medicines, laboratory parameters and other regimen-specific safety measures.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Microbiological and clinical monitoring', 'text', NULL,
    'Monitoring combines symptoms, examination, microbiological testing and safety investigations. Persistent symptoms, delayed microbiological response or clinical deterioration should trigger structured reassessment rather than automatic continuation of the existing plan.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Adherence monitoring', 'text', NULL,
    'Adherence is a shared-care issue. Ask about missed doses without blame. Explore transport, cost, stigma, side effects, work, family responsibilities, mental health and understanding of treatment. Use the least burdensome effective support model available.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Treatment outcomes', 'text', NULL,
    'Treatment outcome definitions should follow the current WHO and national programme framework. Documentation must be accurate because outcomes are used for patient care, programme evaluation and surveillance.',
    2, 4 FROM DUAL WHERE @existed = 0;

-- Module 8: DR-TB, HIV and Comorbidities
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'DR-TB, HIV and Comorbidities', NULL, 8 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 8);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'TB/HIV integrated care', 'text', NULL,
    'HIV testing and appropriate linkage to HIV care are important in DR-TB management. Antiretroviral therapy and TB medicines can interact, and timing and regimen choices should follow current HIV/TB guidance.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Diabetes and other chronic disease', 'text', NULL,
    'Diabetes and other chronic conditions can complicate TB management. Integrated care reduces fragmented follow-up and helps address adherence, drug interactions and treatment safety.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Pregnancy and breastfeeding', 'text', NULL,
    'Pregnancy requires individualized review of disease severity, resistance, medicine safety and current recommendations. Do not rely on outdated lists of \'safe\' or \'unsafe\' drugs; consult current guidance and specialist expertise.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Children and adolescents', 'text', NULL,
    'Children and adolescents require age-appropriate diagnostics, formulations, dosing, safeguarding and psychosocial support. Treatment decisions should follow current paediatric DR-TB guidance.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Mental health and social vulnerability', 'text', NULL,
    'Depression, anxiety, stigma, financial hardship, housing insecurity and other social pressures can affect treatment completion. Patient-centred support is part of effective DR-TB care, not an optional extra.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 9: Infection Prevention and Control
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Infection Prevention and Control', NULL, 9 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 9);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'The hierarchy of controls', 'text', NULL,
    'TB infection prevention uses a hierarchy that includes administrative controls, environmental controls and respiratory protection. No single intervention is sufficient in every setting.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Administrative controls', 'text', NULL,
    'Early recognition, triage, prompt testing, separation of potentially infectious patients and effective referral pathways reduce exposure. Staff should know the facility\'s TB infection-prevention procedures.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Environmental controls', 'text', NULL,
    'Ventilation, airflow management and appropriate environmental design reduce airborne transmission risk. Local engineering and infection-control expertise should guide facility-specific measures.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Respiratory protection', 'text', NULL,
    'Appropriate respirators may be required for healthcare workers and others at risk of exposure. Fit, correct use and programme-level respiratory protection policies matter.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Community and household considerations', 'text', NULL,
    'Patients and families need practical, non-stigmatizing information about ventilation, cough etiquette, treatment adherence and when to seek care. Household contact investigation should follow national policy.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 10: Patient-Centred Care, Counselling and Adherence
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Patient-Centred Care, Counselling and Adherence', NULL, 10 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 10);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Communication skills', 'text', NULL,
    'Use plain language, check understanding and invite questions. Avoid blaming language. Ask what the patient believes about TB and treatment before correcting misinformation.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Stigma and confidentiality', 'text', NULL,
    'DR-TB can carry substantial stigma. Protect confidentiality and involve family or community supporters only with appropriate consent and in accordance with policy.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Managing treatment fatigue', 'text', NULL,
    'Patients may experience exhaustion from long or intensive treatment. Break information into manageable steps, explain the purpose of monitoring and address adverse effects promptly.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Digital and community support', 'text', NULL,
    'Where available and appropriate, digital adherence technologies, phone follow-up and community-based services can complement facility care. Technology should supportÔÇönot replaceÔÇöhuman clinical relationships.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Difficult conversation simulation', 'text', NULL,
    'Scenario: \'These medicines are making me sick. I want to stop.\' A strong response acknowledges the patient\'s experience, assesses urgent safety concerns, explores the specific adverse effects, explains why stopping without clinical review can be dangerous, and arranges prompt assessment and support.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 11: DR-TB Programme Management and Data
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'DR-TB Programme Management and Data', NULL, 11 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 11);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'The patient pathway', 'text', NULL,
    'Effective DR-TB care depends on a connected pathway: identification ÔåÆ testing ÔåÆ resistance characterization ÔåÆ clinical assessment ÔåÆ treatment initiation ÔåÆ monitoring ÔåÆ adherence support ÔåÆ outcome documentation ÔåÆ follow-up.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Data quality', 'text', NULL,
    'Accurate patient identifiers, laboratory results, treatment dates, adverse events and outcomes support safe care and programme accountability. Avoid duplicate records and resolve inconsistencies promptly.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Supply and continuity', 'text', NULL,
    'Interruptions in medicine availability can compromise treatment. Programmes require forecasting, procurement, stock monitoring and rapid escalation of shortages.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Monitoring and evaluation', 'text', NULL,
    'Programme indicators can include diagnostic coverage, treatment initiation, treatment success, loss to follow-up, mortality, adverse events and laboratory turnaround times. Indicators should be interpreted in context rather than used as isolated numbers.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Quality improvement', 'text', NULL,
    'Use PlanÔÇôDoÔÇôStudyÔÇôAct or another structured quality-improvement approach to address bottlenecks such as delayed testing, missed appointments, stock-outs or incomplete adverse-event documentation.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Module 12: Capstone: Integrated DR-TB Clinical Case
INSERT INTO academy_modules (course_id, title, summary, position)
  SELECT @cid, 'Capstone: Integrated DR-TB Clinical Case', NULL, 12 FROM DUAL WHERE @existed = 0;
SET @mid = (SELECT id FROM academy_modules WHERE course_id = @cid AND position = 12);
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Case presentation', 'text', NULL,
    'A 34-year-old adult with previous TB treatment presents with persistent cough, weight loss and treatment interruption history. Rapid molecular testing detects M. tuberculosis and rifampicin resistance. Additional resistance testing is pending. The learner must identify the immediate priorities without prematurely selecting a regimen from memory.',
    2, 1 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Diagnostic reasoning', 'text', NULL,
    'The learner reviews the resistance result, determines what additional susceptibility information is required, checks previous treatment exposure and identifies urgent clinical and infection-control needs.',
    2, 2 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Treatment planning', 'text', NULL,
    'The learner selects the appropriate treatment pathway only after checking the current WHO/national algorithm, eligibility criteria, resistance profile, previous drug exposure, comorbidities, interactions and safety considerations.',
    2, 3 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Monitoring and support plan', 'text', NULL,
    'The learner creates a baseline safety checklist, microbiological monitoring plan, adverse-event surveillance plan and adherence-support strategy. The plan must include escalation triggers.',
    2, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_lessons (module_id, title, kind, source, body, duration_minutes, position)
  SELECT @mid, 'Final competency reflection', 'text', NULL,
    'The learner explains why DR-TB management is a multidisciplinary process involving laboratory services, clinicians, nurses, pharmacists, public-health teams, community services and the patient.',
    2, 5 FROM DUAL WHERE @existed = 0;

-- Final assessment
INSERT INTO academy_assessments (course_id, module_id, title, pass_mark, max_attempts, question_count, shuffle_questions)
  SELECT @cid, NULL, 'Final assessment', NULL, 0, 0, 1 FROM DUAL WHERE @existed = 0;
SET @aid = (SELECT id FROM academy_assessments WHERE course_id = @cid AND module_id IS NULL ORDER BY id LIMIT 1);
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Which statement best describes drug-resistant TB?', 'single',
    'DR-TB is defined by resistance to one or more medicines and requires a resistance-informed management pathway.', 1 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 1);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'TB that is always fatal', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'TB with resistance to one or more TB medicines', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'TB without symptoms', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'TB caused only by bacteria outside the lungs', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Why should TB transmission be explained without blame?', 'single',
    'Patient-centred communication reduces stigma and supports engagement with care.', 2 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 2);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Blame improves adherence', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Stigma can create barriers to care and disclosure', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Patients are never infectious', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Transmission is not airborne', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'MDR-TB includes resistance to which two core medicines?', 'single',
    'MDR-TB is defined by resistance to at least isoniazid and rifampicin.', 3 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 3);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Ethambutol and pyrazinamide', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Rifampicin and isoniazid', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Bedaquiline and linezolid', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Moxifloxacin and pretomanid', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'A rifampicin-resistant result should generally lead to:', 'single',
    'Rifampicin resistance triggers further evaluation and DR-TB management according to the applicable algorithm.', 4 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 4);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Ignoring the result', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Immediate selection of a regimen from memory', 0, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Entry into an appropriate DR-TB evaluation pathway', 1, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Stopping all TB testing', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'What is a major advantage of rapid molecular testing?', 'single',
    'Rapid molecular testing shortens time to identification of TB and selected resistance.', 5 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 5);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'It never needs quality control', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It can identify TB and selected resistance rapidly', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It replaces all cultures', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It eliminates clinical assessment', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Why does specimen quality matter?', 'single',
    'Adequate collection and handling are essential for reliable laboratory results.', 6 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 6);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Only because of cost', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Poor specimens can compromise diagnostic accuracy', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It does not matter with molecular tests', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It determines the patient\'s age', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'What is a key principle of DR-TB regimen selection?', 'single',
    'DR-TB treatment must be individualized within current WHO and national algorithms.', 7 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 7);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Use the same regimen for everyone', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Base selection on resistance, eligibility, previous exposure, safety and current guidance', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Choose the cheapest medicine only', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Avoid all monitoring', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'BPaLM contains:', 'single',
    'BPaLM stands for bedaquiline, pretomanid, linezolid and moxifloxacin.', 8 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 8);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Bedaquiline, pretomanid, linezolid and moxifloxacin', 1, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Bedaquiline, rifampicin, isoniazid and ethambutol', 0, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Pretomanid, rifampicin and pyrazinamide', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Linezolid, ethambutol and rifampicin', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'What is the safest approach when a guideline has changed?', 'single',
    'DR-TB recommendations evolve; clinicians should verify the current applicable guidance.', 9 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 9);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Use an old regimen from memory', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Verify the current WHO and national guidance', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Ignore resistance results', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Ask the patient to choose', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Which adverse effect is particularly important with linezolid?', 'single',
    'Linezolid can cause peripheral neuropathy and other serious toxicities requiring monitoring.', 10 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 10);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Permanent hair growth', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Peripheral neuropathy', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Blue skin in every patient', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Immediate deafness in every patient', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Why is medication reconciliation important?', 'single',
    'A complete medication history helps identify interactions and avoid preventable harm.', 11 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 11);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'It is only administrative', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Drug interactions and duplicated therapies can affect safety and efficacy', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It replaces laboratory testing', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'It guarantees adherence', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'What should a patient with new visual symptoms during treatment do?', 'single',
    'New visual symptoms can indicate serious toxicity and require prompt assessment.', 12 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 12);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Ignore them', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Wait until treatment completion', 0, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Receive prompt clinical assessment', 1, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Stop every medicine permanently without review', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'What is pharmacovigilance?', 'single',
    'Pharmacovigilance supports safe medicine use and programme learning.', 13 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 13);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Marketing medicines', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Systematic detection, assessment and management/reporting of medicine-related safety problems', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'A method of diagnosing TB without tests', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'A type of surgery', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Which combination best represents treatment monitoring?', 'single',
    'DR-TB monitoring integrates clinical response, microbiology and medicine safety.', 14 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 14);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Symptoms only', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Laboratory tests only', 0, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Clinical, microbiological and safety monitoring', 1, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Patient opinion only', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'What is a non-blaming adherence question?', 'single',
    'Open, non-judgmental questions reveal barriers that can be addressed.', 15 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 15);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Why are you so careless?', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'You clearly don\'t want treatment.', 0, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'What made it difficult to take your medicines as planned?', 1, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Did you deliberately sabotage treatment?', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Why is HIV care integrated into DR-TB management?', 'single',
    'Integrated care supports safety, treatment timing and continuity.', 16 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 16);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'HIV has no effect on TB', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'TB medicines and HIV medicines can interact and both conditions require coordinated care', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'ART is never used', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Only because of paperwork', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'How should pregnancy affect DR-TB care?', 'single',
    'Pregnancy requires current, individualized risk-benefit assessment.', 17 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 17);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Ignore pregnancy', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Use an individualized assessment with current guidance and specialist input', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Automatically stop all TB treatment', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Use an old medicine list', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Which is part of the TB infection-control hierarchy?', 'single',
    'Effective TB infection prevention uses a hierarchy of complementary controls.', 18 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 18);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Administrative controls', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Environmental controls', 0, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Respiratory protection', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'All of the above', 1, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'A patient says, \'I want to stop because these medicines make me sick.\' Best first response?', 'single',
    'The response should address safety, empathy and timely clinical assessment.', 19 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 19);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Dismiss the complaint', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Acknowledge the concern, assess the symptoms and arrange prompt clinical review', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Tell the patient to stop everything', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Threaten the patient', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Why are accurate DR-TB records important?', 'single',
    'High-quality data supports both individual and population-level care.', 20 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 20);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Only for billing', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'They support patient safety, surveillance, programme evaluation and continuity of care', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'They are optional', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'They replace clinical judgement', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'A rifampicin-resistant result is available but additional resistance testing is pending. What should the learner do?', 'single',
    'Resistance-informed management requires the relevant diagnostic and clinical information before final regimen selection.', 21 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 21);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Choose a regimen solely from the rifampicin result', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Follow the current DR-TB diagnostic pathway while assessing the patient and obtaining required information', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Tell the patient there is no treatment', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Wait indefinitely', 0, 4 FROM DUAL WHERE @existed = 0;
INSERT INTO academy_questions (assessment_id, prompt, kind, explanation, position)
  SELECT @aid, 'Which is the strongest capstone approach?', 'single',
    'DR-TB care is multidisciplinary and requires integrated reasoning.', 22 FROM DUAL WHERE @existed = 0;
SET @qid = (SELECT id FROM academy_questions WHERE assessment_id = @aid AND position = 22);
INSERT INTO academy_options (question_id, label, is_correct, position)
  SELECT @qid, 'Memorize one regimen', 0, 1 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Integrate diagnosis, resistance, eligibility, safety, monitoring and patient support', 1, 2 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Ignore adverse effects', 0, 3 FROM DUAL WHERE @existed = 0
  UNION ALL
  SELECT @qid, 'Focus only on laboratory results', 0, 4 FROM DUAL WHERE @existed = 0;

